<?php 
//------------------------------------------------------------------------------
//<INFO >
//     This file was generated by MyPhpGuard 1.3.54.5
//     
//     Date:07/01/2018 7:53:55 AM
//
// </INFO >
//------------------------------------------------------------------------------
 /**
 * 
 * @category    
 * @package    
 * @author      djavasoft <support@djavasoft.com>
 * @copyright   2018 djavasoft
 * @license     
 * @version    
 * @link   http://djavasoft.com
 *      
 */
?>
<link rel='stylesheet'   href='<?php echo $CORE_URL;?>/assets/css/dataTables.checkboxes.css' type='text/css' media='all' />
<script type='text/javascript' src='<?php echo $CORE_URL;?>/assets/js/dataTables.checkboxes.min.js'></script>

<script>
var ajaxBarang="data.php?kasirBarang=daftar_barang";
shortcut.add("f1",function() {
$('#doBarang').modal('show');
});
shortcut.add("f2",function() {
$('#qty').focus();
});
shortcut.add("f3",function() {
$('#num2').focus();
});
shortcut.add("end",function() {
$('#doBayarKasir').modal('show');
});
$(document).ready(function() {
	
	   // Handle form submission event 
$('#frm-barang').on('submit', function(e){
  var form = this;
  
  var rows_selected = tableBarang.column(0).checkboxes.selected();
     var ids=rows_selected.join(',');
//	$('#barang-console-rows').val(ids);      
	$('#loadBarcode').load('data.php?barcode=img&ids='+ids);
     

});


$('#kodeBarang').focus();
var tableBarang = $('#tableBarang').DataTable( {
"language": {
"emptyTable": "No data available in table"
},
scrollY: '50vh',
"scrollX": true,
select: true,
keys: true,
"pageLength": 10,
"lengthMenu": [ 5,10, 25, 50 ],
"paginate":true,
"bLengthChange": false,
"info":false,
"length":false,
"ajax": ajaxBarang ,
"pagingType": "simple",

"order": [[ 0, "desc" ]],
"select": {
 "style": "multi"
},
"columnDefs": [ 
{
	"targets": 0,
	"checkboxes": {
	"selectRow": true,
	},
	"orderable": false,

}
]
} );




});


</script>
